// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGpOiIoSBx8t_2CJSAZxuaFMKJJPdbUM',
    appId: '1:318288626473:web:e261d9bd6ad253a3686d38',
    messagingSenderId: '318288626473',
    projectId: 'fanpage-94300',
    authDomain: 'fanpage-94300.firebaseapp.com',
    storageBucket: 'fanpage-94300.appspot.com',
    measurementId: 'G-H4RBWZ3Z9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFtRvTHd8xuZqpYJXVPoUzlN7jtVKDgY',
    appId: '1:318288626473:android:1a84ec2fb54a96ef686d38',
    messagingSenderId: '318288626473',
    projectId: 'fanpage-94300',
    storageBucket: 'fanpage-94300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJf95U4bC93bZWDn2U7rWemTz6z2R4Xw8',
    appId: '1:318288626473:ios:2a9fe70b7e991da5686d38',
    messagingSenderId: '318288626473',
    projectId: 'fanpage-94300',
    storageBucket: 'fanpage-94300.appspot.com',
    androidClientId: '318288626473-ckfcjit3aq7tqpmd26mhqlo3evkd45au.apps.googleusercontent.com',
    iosClientId: '318288626473-4bl8lfefhl4u7pfpp6m5nh44fg3e3v04.apps.googleusercontent.com',
    iosBundleId: 'com.csc4360.fan-page-app',
  );
}
